### ISSUE TITLE
Possivel falha UTF8 e outras dicas

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/queriDO#1]
As páginas HTML de matérias do DO-RJ (rio.rj.gov.br) possuem boa estrutura e conteúdo fiel,  uma pena que não cumpram minimamente com os padroões  vigentes ([ePING](http://eping.governoeletronico.gov.br/), IETF, W3C, etc. recomendam [UTF-8](https://en.wikipedia.org/wiki/UTF-8)) nem o cabeçalho mínimo de uma página HTML (deveria extressar charset no `meta`).

No [getHtm.py](https://github.com/joaomeirelles/meuqueridodiario/blob/master/getHtm.py) é suposto que TODAS as páginas façam uso de  charset `iso-8859-1`... Até parece que sim, mas não é correto supor (forçar que seja), o mais seguro é _detectar automaticamente_ a origem antes de converter. Talvez simplesmente mudando 
   `materia[0][1:].decode('iso-8859-1').encode('utf8')` 
para
   `materia[0][1:].encode('utf8')` 
o Python já se encarregue sozinho disso. Testar: se ficar tudo igual, sinal que o auto-detect funcionou (!). Eventualmente corrigirá algum caso de `windows-1250` ou [BOM](https://en.wikipedia.org/wiki/Byte_order_mark).

---
## Comentários

O http://validator.w3.org/ detectou também `iso-8859-1` de  amostras,  ainda assim os próprios mantenedores do validador lembram que é complicado supor o charset de origem: _[Checking the character encoding using the validator](https://www.w3.org/International/questions/qa-validator-charset-check.en)_. Como há uma avalanche de pequenos problemas, o ideal é ter ao menos o charset bem resolvido:
- [Exemplo1](http://doweb.rio.rj.gov.br/do/navegadorhtml/mostrar.htm?id=367406&edi_id=3205): matéria de 2016, parece tudo em ordem, e confirma `iso-8859-1`.
- [Exemplo2](http://doweb.rio.rj.gov.br/do/navegadorhtml/mostrar.htm?id=151434&edi_id=2369): matéria mais antiga e diagramada de outra forma, seus problemas já foram [destacados antes aqui](https://github.com/ppKrauss/queriDO/blame/master/html/2369-151434.html) ([relatório](https://github.com/ppKrauss/queriDO/issues/1#issuecomment-239147779)).  O validador W3 manteve seu parecer sobre charset, mas encontrou literalmente [uma centena de problemas](http://validator.w3.org/check?uri=http%3A%2F%2Fdoweb.rio.rj.gov.br%2Fdo%2Fnavegadorhtml%2Fmostrar.htm%3Fid%3D151434%26edi_id%3D2369&charset=%28detect+automatically%29&doctype=Inline&group=1&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices).

Para corrigir todos os problemas subsequentes, basta "limpar" o HTML tendo em vista que a estrutura das matérias é de apenas parágrafos. Isso foi feito com sucesso por um script PHP, [clean.php](https://github.com/ppKrauss/queriDO/blob/master/src/clean.php), que pode ser facilmente traduzido para Python (eu ajudo).

Outra dica: iniciativa similar, que já grava em nomes de pasta adequados, podendo ser adaptado para o padrão ePING de nomes (URNs) de normas,  https://github.com/andresmrm/trazdia

**Comment by JaTvoiRabotnik** [comment]
Nao sei se e relevante, mas o [script desbrutalizador](https://github.com/rafaeusantana/docsolr/blob/master/scripts/desbrutalizador.py) do [Diario Livre](https://github.com/rafaeusantana/docsolr) tem uma funcaozinha (ler_txt_hostil) que faz algo do genero

**Comment by ppKrauss** [comment]
Olá @JaTvoiRabotnik , inclui os "objetivos" no [README.md](https://github.com/okfn-brasil/queriDO/blob/master/README.md) para você e demais colaboradores entenderem melhor as metas. Sim, o "desbrutalizador" pode ser generalizado para uso aqui... Mas antes precisaremos da sua ajuda na resolução aqui da *issue1*: que tal, pode fazer testes e corrigir (ou nos passar aqui as suas conclusões)?

**Comment by JaTvoiRabotnik** [comment]
Ve se [esse pull request](https://github.com/okfn-brasil/queriDO/pull/5) resolve o issue, por favor.

**Comment by JaTvoiRabotnik** [comment]
Da pra fechar esse issue com meu commit?

**Comment by JaTvoiRabotnik** [comment]
Acabei de notar que o script getMateria.py tem o mesmo problema, potencialmente.

Vou tentar achar uma solução mais genérica, que possa ser usada pelos dois scripts.

**Comment by ppKrauss** [comment]
Sem o diff dos HTMLs anterores (apagados) ficamos sem saber o que de fato melhorou... 
Mas [na interface](https://okfn-brasil.github.io/queriDO/) confira por exmeplo o 116265, ainda tem falha.

**Comment by JaTvoiRabotnik** [comment]
getHTML.py nao extrai os documentos, apenas os indices das materias. O
objetivo do script e de criar arquivos CSV, um pra cada edicao do DO, com
um dicionario para os links das materias.
HTMLs anteriores foram restaurados no ultimo commit. Nao foram re-generados, sao os originais mesmo.

**Comment by ppKrauss** [comment]
Confere se não é problema no original do site. (baixa com `wget` para ver bruto, pois navegador pode estar "arrumando").. Ultimo caso, como em problemas de [OCR](https://en.wikipedia.org/wiki/Optical_character_recognition), uma boa regular expression arruma.

**Comment by JaTvoiRabotnik** [comment]
Como assim, nao te entendo. Que problema? Eu disse que o objetivo do script getHtml.py nao e de extrair o texto, como o que aparece quando se clica em um dos links da sua interface. Tudo o que o script faz e criar um dicionario para a localizacao das materias. Tem que fazer um curl pra cada um deles pra pegar as materias.
Eu creio que pegar as materias seja o objetivo do script getMateria.py.

**Comment by ppKrauss** [comment]
Me refiro ao [problema comentado acima](https://github.com/okfn-brasil/queriDO/issues/1#issuecomment-272514867). Ocorre em dezenas de arquivos, mas fiquemos com o exemplo do 116265, 
 
> Â Â Diário Oficial nº : ...

esse " Â Â ", parece algum remanescente de `&nbsp;`... e importante o que comentei: ver se o problema não está no original (pois aí não é bug nosso! e fechamos essa *issue*).

**Comment by JaTvoiRabotnik** [comment]
Pois e, acho que nao estamos falando da mesma coisa...

Os arquivos HTML **nao foram modificados**. **Nao foram gerados de novo**. **Ainda sao os mesmos**.

Eu corrigi o script getHtml.py, que quando rodado, nao altera em nada os arquivos na pasta html. Tudo que o script faz e gerar varios arquivos CSV com dicionarios que levam as materias individuais (em html).

**Comment by JaTvoiRabotnik** [comment]
getMateria.py faz uso de uma biblioteca chamada [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/), que extrai texto e ja trata de encodings. Vou destrinchar ela pra entender como usar direito.

**Comment by ppKrauss** [comment]
Oi Marco, se achar mais simples tenta reproduzir o get com cURL, um simples
  wget -c
http://doweb.rio.rj.gov.br/do/navegadorhtml/mostrar.htm?id=367406&edi_id=3205
nao funciona (o servidor recusa).
Ai fazemos o tira-teima: se o curl vem com pau de charset é pau do original
não do nosso leitor.






2017-01-17 15:08 GMT-02:00 Marco Zanchi <notifications@github.com>:

**Comment by JaTvoiRabotnik** [comment]
Na pagina original da materia 116265 (da edicao 2217), o caracter **Â** vem da seguinte linha:

```
<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
8.5pt'><span style='font-size:7.0pt;font-family:"Arial","sans-serif"'>&nbsp;</span></p>
```

Entao o problema e com certeza no nosso codigo. Estou refactorando o script getMateria pra ver se eu consigo usar o BeautifulSoup pra extrair os dados, como era a intencao original. Ai o clean.php (que parece ser a fonte do problema de encoding) nao sera mais necessario. Claro que existe aqui um vies da minha parte, pq eu nao me sinto muito confortavel com PHP, e tmbm por que acho que so o script getMateria deveria ser capaz de pegar os dados sem precisar de tratamento posterior.

Vou abrir um outro issue pra fazer o trabalho no getMateria, assim a discussao la fica mais limpa.

**Comment by ppKrauss** [comment]
> > > Na pagina original da materia 116265 (da edicao 2217), o caracter *Â* vem
> > > da seguinte linha:
> >
> > Entao o problema e com certeza no nosso codigo. Estou refatorando o script getMateria
> > pra ver se eu consigo usar o BeautifulSoup pra extrair os dados, como era a intencao original. (...)

Fique a vontade com a linguagem... Essa coisa de UTF8 é o "passo zero": trazer o original bruto e condificar em formato padrao HTML com UTF8... Pode até ser um script no shell com wget ou curl provando o conceito.
Talvez gravando arquivos originais (registrando no git inclusive) numa pasta /originais seja mais facil de conferir o que o "limpador" faz de bom ou de ruim.

PS: o clean.php eu fiz mas larguei pela metade quando vi que o melhor era capturar já os originais em UTF8. Se retomar posso ajudar... Também tem a opção de usar o http://htmlpurifier.org/  com Composer.


UPDATE abril/2017:  a conversão do "HTML livre" para XML (HTML5 poliglota UTF8) é a mais importante, se falhar em algum momento, vi a sugestão de usar http://www.nokogiri.org/
