### ISSUE TITLE
uniformizar extensão

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/queriDO#22]
pastas `/html` e `/newhtml` precisam ter exatamente os mesmos nomes de arquivo... Parece que um está com `.htm`  e outro com `.html`. Arrumar no Python.

**Comment by JaTvoiRabotnik** [comment]
Por que eles precisam ter o mesmo nome? Se e realmente importante, eu sugiro corrigir os arquivos que estao como *.htm para transforma-los em *.html, ja que esse e o padrao para arquivos html (ja estamos no seculo XXI, e extensoes de arquivos em Windows podem ter mais que 3 letras).

**Comment by ppKrauss** [comment]
Ainda vamos melhorar tudo isso, provavelmente ficando apenas com os originais em filesystem e o restante controlado por PosgreSQL... Mas por hora é o que temos para discutir e mostrar: o mais facil, já que a pasta html foi gerada por caixa preta, é você corrigir a sua pasta *newhtml*, gerando novamente com a extenção que o git já vinha adotando.

**Comment by JaTvoiRabotnik** [comment]
OK, mas isso e desgastante. Nao considero isso algo importante. Eu teria que trocar meu branch local, apagar os arquivos, mudar o codigo, re-gerar os arquivos, fazer outro pull request. Sinceramente nao me vejo fazendo isso agora.
Fique a vontade de fazer a mudanca voce mesmo.

**Comment by ppKrauss** [comment]
Ok, usei um shell script meio feio mas funcionou com `git mv` de cada file... resolvidas as extensões. Faltava ajustar o Javascript... Teste a navegação com https://okfn-brasil.github.io/queriDO/  variando "Filtrado" e "Original", parece agora que funciona!
