### ISSUE TITLE
fechar tag v0.1 para apresentação e balanço

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/queriDO#27]
Adicionando mais algumas marcações (CNPJ, data, código de contrato, valor, etc.) mais pode-se ilustrar a estratégia:

 1. repositório das cópias hoologadas (UTF-8 e endosso de "cópia fiel"). 
 2. obtenção do conteúdo filtrado e estruturado;
 3. marcação (anotação semântica) do conteúdo.

e com isso discutir e fazer um balanço geral do projeto para iniciarmos de forma mais definitiva e organizada as implementações.

Com uma [tag de "versão 0.1"](https://github.com/okfn-brasil/queriDO/releases) estabelecemos o referencial do que foi feito até o momento.

**Comment by JaTvoiRabotnik** [comment]
Completado com commit do Peter. Agora temos pelo menos algo para mostrar para as partes interessadas.
