### ISSUE TITLE
Arquivos inexistentes

### ISSUE THREAD

**Issue by JaTvoiRabotnik** [okfn-brasil/queriDO#4]
Nao consigo entender o final do getHtm.py. Ele refere a um diretorio htmLinks, onde deveriam se encontrar diversos .csv, mas quem deveria te-los gerado? Meu script morre nessa hora...

**Comment by ppKrauss** [comment]
Chi...  o pessoal anda de férias, talvez tenhamos de bolar uma "reengenharia" partindo do [data/htmlMeta1.csv](https://github.com/okfn-brasil/queriDO/blob/master/data/htmlMeta1.csv) que fui eu que gerem com base num zip ja pronto deles.

* exemplo de matéria recente: http://doweb.rio.rj.gov.br/do/navegadorhtml/mostrar.htm?id=395165&edi_id=3322

* exemplo de uma das nossas, primeira linha do CSV  http://doweb.rio.rj.gov.br/do/navegadorhtml/mostrar.htm?id=2328&edi_id=1784  que bate com 2328  em nosso https://okfn-brasil.github.io/queriDO/

**Comment by JaTvoiRabotnik** [comment]
Da um assign desse issue pra mim que eu dou uma olhada. Acho que vou aproveitar e documentar um pouco mais o código tmbm, pq ta meio bagunça...

**Comment by JaTvoiRabotnik** [comment]
[Esse pull request](https://github.com/okfn-brasil/queriDO/pull/8) resolve esse issue. Da uma olhada e fecha se achar que ta tudo bom.

Pra manter documentado: o script que gera os CSVs. Nao estava acontecendo por que o diretorio nao existia. Criar um diretorio vazio resolveu o problema.
Esses CSVs contem dicionarios, um por edicao, das materias. De la a gente pega os links para as materias (na ultima entrada de cada linha do dicionario).

**Comment by JaTvoiRabotnik** [comment]
Ops... git ignora diretorios vazios...
Perai que vou consertar isso.

**Comment by ppKrauss** [comment]
Aproveita  e desfaz o apagão dos HTMLs, quero justamente ver o DIFF!!!

**Comment by JaTvoiRabotnik** [comment]
Aceita os dois pull requests que eles voltam. Ainda estavam no meu master :)

**Comment by ppKrauss** [comment]
Ok, foi

2017-01-13 15:46 GMT-02:00 Marco Zanchi <notifications@github.com>:
