### ISSUE TITLE
Onde manter artefatos

### ISSUE THREAD

**Issue by JaTvoiRabotnik** [okfn-brasil/queriDO#9]
> Objetivo 4: Criar convençoes para armazenar aqui no git os originais fornecidos, e os textos processados para recuperação de estrutura.

Nao concordo com isso. Acho que aqui no repositorio deveriamos manter somente o codigo fonte. Vide o [outro issue falando de Hosting](https://github.com/okfn-brasil/queriDO/issues/7).

**Comment by ppKrauss** [comment]
@JaTvoiRabotnik,  a sua colocação faz sentido... Para continuar a discussão talvez precisemos de algum aprofundamento: 

1.  A perspectiva é ir além da coleta automática de conteúdos desejados... É fazer um pouco de "trabalho braçal" sobre os HTMLs, então esse trabalho não pode ser perdido. <br>Exemplo: com auxílio de *regular expressions*, polimento dos dados, etc. é que chegaremos em bons resultados,  de modo que os HTMLs  não ressurgirão magicamente de  um só click, precisam ser preservados.

2. Os "dados" da pasta [html](https://github.com/okfn-brasil/queriDO/tree/caea4af55fecb7815885cc886622557578e1cd79/html) formam um [*text corpus*](https://en.wikipedia.org/wiki/Text_corpus), é uma questão metodológica e de disciplina para monitoramento das falhas e da evolução dos algoritmos. <br/>OOPS, você sumiu com a pasta! (e eu já aprovei o sumisso ;-)  

3. A OKFn ainda não possui mecanismos de [preservação de dados](https://en.wikipedia.org/wiki/Digital_preservation) (vide algo sério como  LOCKSS ou pelo menos IPFS)... Então se o governo pisa na bola ou muda as "regras do jogo", tudo fica perdido. Hoje a única coisa que garante certa preservação é o [LexML](http://www.lexml.gov.br/), mas são apenas metadados, ele não armazena HTML.

**Comment by JaTvoiRabotnik** [comment]
Compreendido.

Algo a se colocar na documentacao da metodologia entao, vide[ issue 6](https://github.com/okfn-brasil/queriDO/issues/6)
